### ISSUE TITLE
Allow other contracts to increase/decrease voting power

### ISSUE THREAD

**Issue by aaitor** [bancorprotocol/gov-contracts#1]
Allow other contracts to increase/decrease voting power indirectly by notifying the contract that the user staked BNT elsewhere (This would be contributed back to the yearn project by Bancor):
- [ ] ~Governor controlled 3rd party staking contracts whitelist https://github.com/bancorprotocol/gov-contracts/issues/10~
- [ ] ~The contracts should be able to call stakeAdded/stakeRemoved functions (see suggested design below) and the governance should adjust voting rights based on the amounts given https://github.com/bancorprotocol/gov-contracts/issues/11~
- [ ] ~If the voter is locked, calling stakeRemoved should revert https://github.com/bancorprotocol/gov-contracts/issues/12~
