### ISSUE TITLE
UX Branding and adjustments

### ISSUE THREAD

**Issue by aaitor** [bancorprotocol/gov-contracts#3]
Frontend adjustments to adapt to Bancor branding

- [x] Create governance page and add it to the navigation of the bancor web app https://github.com/bancorprotocol/webapp/issues/174
- [x] Create Stake widget https://github.com/bancorprotocol/webapp/issues/173
- [x] Create proposal List https://github.com/bancorprotocol/webapp/issues/175
- [x] Create proposal details view / vote for/against page https://github.com/bancorprotocol/webapp/issues/176
- [x] Create stake overlay https://github.com/bancorprotocol/webapp/issues/177
- [x] Create unstake overlay https://github.com/bancorprotocol/webapp/issues/178
- [ ] Create new proposal overlay / page https://github.com/bancorprotocol/webapp/issues/179
