### ISSUE TITLE
Code cleanup before audit

### ISSUE THREAD

**Issue by aaitor** [bancorprotocol/gov-contracts#4]
- [x] Make sure the new contract abides by the copyright constraints of the original one https://github.com/bancorprotocol/gov-contracts/issues/13
- [x] Remove all unused dependencies https://github.com/bancorprotocol/gov-contracts/issues/5
- [x] Remove the register functionality https://github.com/bancorprotocol/gov-contracts/issues/14
- [x] Move stake/withdraw functions to the main governance contract https://github.com/bancorprotocol/gov-contracts/issues/6
- [x] Update repo settings/config etc. to be up to par with the contracts-solidity repo https://github.com/bancorprotocol/gov-contracts/issues/7
- [x] Upgrade code/conventions to be up to par with other Bancor contracts https://github.com/bancorprotocol/gov-contracts/issues/8
- [x] Add tests / test coverage https://github.com/bancorprotocol/gov-contracts/issues/9
